runtime: php
env: flex
api_version: 1
runtime_config:
  document_root: CRDO
env_variables:
  GOOGLE_STORAGE_BUCKET: staging.stoked-energy-210523.appspot.com
  MYSQL_DSN: mysql:dbname=Site_Users;unix-socket=/cloudsql/stoked-energy-210523:us-east1:mcgtechdb1
  MYSQL_USER: webguest
  MYSQL_PASSWORD: M2Ykx19P!rm&
beta_settings:
  cloud_sql_instances: "stoked-energy-210523:us-east1:mcgtechdb1"

handlers:
# Serve PHP
- url: /.php
  script: auto

# Serve everything else
- url: /.*
  static_dir: CRDO
