runtime: php72
env_variables:
  GOOGLE_STORAGE_BUCKET: mcgstorage
  MYSQL_DSN: mysql:unix_socket=/cloudsql/mcgtechdb1;dbname=Site_Users
  MYSQL_USER: webguest
  MYSQL_PASSWORD: M2Ykx19P!rm&

handlers:
# Serve Css
- url: /stylesheets
  static_dir: stylesheets

# Serve images as static resources
- url: /(.+\.(gif|png|jpg|jpeg))$
  static_files: \1
  upload: .+\.(gif|png|jpg|jpeg)$

# Serve other pages
- url: .*
  script: auto
