runtime: php55
env: flex
entrypoint: serve index.php
api_version: 1
runtime_config:
  document_root: .
  skip_files: xyz.htaccess.php

handlers:
# Serve PHP
- url: /(.+\.php)$
  script: \1

# Serve images as static resources
- url: /(.+\.(gif|png|jpg|jpeg))$
  static_files: \1
  upload: .+\.(gif|png|jpg|jpeg)$
