runtime: php
env: flex
api_version: 1
runtime_config:
  document_root: CRDO
env_variables:
  GOOGLE_STORAGE_BUCKET: staging.stoked-energy-210523.appspot.com
  cloudsql_connection_name: stoked-energy-210523:us-east1:mcgtechdb1
  cloudsql_database_name: Site_Users
  cloudsql_user: webguest
  cloudsql_password: M2Ykx19P!rm&
  cloudsql_port: 3306

handlers:
# Serve PHP
- url: /.php
  script: auto

# Serve everything else
- url: /.*
  static_dir: CRDO

