runtime: php72
env: flex
api_version: 1
runtime_config:
  document_root: .
  skip_files: xyz.htaccess.php

handlers:
# Serve PHP
- url: /(.+\.php)$
  script: \1
  
# Serve images as static resources
- url: /(.+\.(gif|png|jpg|jpeg))$
  static_files: \1
  upload: .+\.(gif|png|jpg|jpeg)$

# Splash Page
- url: .*
  script: index.php
