runtime: php72
env_variables:
  GOOGLE_STORAGE_BUCKET: mcgstorage
  MYSQL_DSN: mysql:unix_socket=/cloudsql/mcgcloudsql;dbname=MCGDB
  MYSQL_USER: root
  MYSQL_PASSWORD: Gs!9#4fv16+Ll
entrypoint: serve index.php
api_version: 1
runtime_config:
  document_root: .
  skip_files: xyz.htaccess.php

handlers:
# Serve PHP
- url: /(.+\.php)$
  script: \1

# Serve images as static resources
- url: /(.+\.(gif|png|jpg|jpeg))$
  static_files: \1
  upload: .+\.(gif|png|jpg|jpeg)$
