runtime: php55
api_version: 1

handlers:
# Splash Page
- url: /.*
  script: index.html
  application_readable: true

# Serve images as static resources
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true
  
# Serve php scripts
- url: /(.+\.php)$
  script: \1
